siteConfig:
  title: My Site
  description: About this website..
  author: My Name
  email: my@email.com
  url: https://example.com
plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-generate-feed
    options:
      atomFeed: true
theme: ./packages/saber-theme-typing/src
themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    dribbble: username
    facebook: username
    flickr: username
    github: username
    instagram: username
    linkedin: username
    pinterest: username
    twitter: username
    youtube: username
    telegram: username
    microdotblog: username
    googleplus: username
    rss: true
  disqus: disqus-short-name