siteConfig:
  title: GeekPlux
  avatar: ./avatar.jpg
  url: https://geekplux.com
  # pagination:
  #   prevPage: 上一页
  #   nextPage: 下一页
  #   prevPost: 上一篇
  #   nextPage: 下一篇
plugins:
  - resolve: saber-plugin-query-posts
    options:
      perPage: 7
  - resolve: saber-plugin-generate-feed
    options:
      atomFeed: true
theme: ./packages/saber-theme-sea/src
themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  # social:
  #   dribbble: username
  #   facebook: username
  #   flickr: username
  #   github: username
  #   instagram: username
  #   linkedin: username
  #   pinterest: username
  #   twitter: username
  #   youtube: username
  #   telegram: username
  #   microdotblog: username
  #   googleplus: username
  #   rss: true
  disqus: geekplux
# build:
#   loaderOptions:
#     sass:
#       data: '@import "../styles/variables.scss";'